metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.12.21, mac: '14:b3:1f:2d:7f:13', disk: sda, network_interface: enp1s0}
        metal1: {ansible_host: 192.168.12.22, mac: 'd8:9e:f3:76:b2:7b', disk: sda, network_interface: enp1s0}
        metal2: {ansible_host: 192.168.12.23, mac: '14:b3:1f:0a:be:22', disk: sda, network_interface: enp1s0}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.12.24, mac: '14:b3:1f:0d:78:f1', disk: sda, network_interface: enp1s0}
